from typing import Optional

from constants import MODEL_COST_PER_MILLION_TOKENS
from openai.types.responses import Response


def get_output_token_from_response(response: Response) -> int:
    """Extract the number of output (completion) tokens from an OpenAI response.

    Args:
        response (Response): The OpenAI API response object containing usage
            information.

    Returns:
        int: The number of completion (output) tokens generated by the model.
    """
    return response.usage.completion_tokens


def get_input_token_from_response(response: Response) -> int:
    """Extract the number of input (prompt) tokens from an OpenAI response.

    Args:
        response (Response): The OpenAI API response object containing usage
            information.

    Returns:
        int: The number of prompt (input) tokens sent to the model.
    """
    return response.usage.prompt_tokens


def calculate_token_cost(response: Response, model_name: str) -> float:
    """Calculate the total token cost for a model response.

    This function computes the cost of both input and output tokens based on
    the pricing defined in ``MODEL_COST_PER_MILLION_TOKENS``. For GPT-5 models,
    reasoning tokens are included in the output cost calculation.

    Args:
        response (Response): The OpenAI API response object containing token
            usage details.
        model_name (str): The name of the model used for the request.

    Returns:
        float: The total cost of the request based on token usage.
    """
    input_tokens = get_input_token_from_response(response=response)
    output_tokens = get_output_token_from_response(response=response)
    input_cost = input_tokens * (
        get_input_cost_for_model(model_name=model_name) / 1_000_000
    )
    if "5" in model_name:
        output_cost = get_gpt5_output_cost(model_name=model_name, response=response)
    else:
        output_cost = output_tokens * (
            get_output_cost_for_model(model_name=model_name) / 1_000_000
        )
    return input_cost + output_cost


def get_gpt5_output_cost(model_name: str, response: Response) -> float:
    """Calculate the full output cost for GPT-5 models including reasoning tokens.

    This function sums visible output tokens and hidden reasoning tokens, then
    applies the model's output token cost.

    Args:
        model_name (str): The GPT-5 model name.
        response (Response): The OpenAI API response object containing token
            usage details.

    Returns:
        float: The total output cost for the GPT-5 model response.
    """
    print(f"Calculating full output cost for: {model_name}")
    reasoning_tokens = get_gpt5_reasoning_token(response=response)
    output_tokens = get_output_token_from_response(response=response)
    total_output_tokens = reasoning_tokens + output_tokens
    return total_output_tokens + (
        get_output_cost_for_model(model_name=model_name) / 1_000_000
    )


def get_gpt5_reasoning_token(response: Response) -> int:
    """Extract the number of reasoning tokens from a GPT-5 response.

    Reasoning tokens represent hidden internal tokens generated by GPT-5
    reasoning models and are billed as output tokens.

    Args:
        response (Response): The OpenAI API response object containing detailed
            completion token information.

    Returns:
        int: The number of reasoning tokens used by the model.
    """
    return response.usage.completion_tokens_details.reasoning_tokens


def get_input_cost_for_model(model_name: str) -> float | None:
    """Retrieve the input token cost per million tokens for a given model.

    Args:
        model_name (str): The name of the model.

    Returns:
        float | None: The input cost per million tokens if available,
        otherwise ``None`` if an error occurs.
    """
    try:
        model_cost = MODEL_COST_PER_MILLION_TOKENS[model_name]["i"]
        return model_cost
    except AttributeError as e:
        print(f"Error: {e}")


def get_output_cost_for_model(model_name: str) -> Optional[float]:
    """Retrieve the output token cost per million tokens for a given model.

    Args:
        model_name (str): The name of the model.

    Returns:
        float | None: The output cost per million tokens if available,
        otherwise ``None`` if an error occurs.
    """
    try:
        model_cost = MODEL_COST_PER_MILLION_TOKENS[model_name]["o"]
        return model_cost
    except AttributeError as e:
        print(f"Error: {e}")
