import operator
from typing import Annotated, Any, TypedDict


class AgentState(TypedDict):
    """Represents the state schema for the graph-based agent.

    This class defines the structure of the shared state passed between nodes in the
    LangGraph workflow. It utilizes `Annotated` with `operator.add` for the message
    history to ensure that new messages are appended rather than overwritten during
    state updates.

    Attributes:
        message: A list of messages (human, AI, or tool) that forms the conversation
            history. Appends automatically via the addition operator.
        pending_tool_calls: A list of tool calls generated by the model that are
            waiting to be executed.
        awaiting_approval: A flag indicating if the workflow is paused waiting for
            human intervention on sensitive actions.
        approval_granted: A boolean tracking whether the user has authorized the
            pending tool execution.
        iteration_count: An integer counter used to track the number of reasoning
            loops to prevent infinite cycles.
        should_exit: A control flag to signal that the graph should transition
            to the END node.
        last_user_input: The most recent string input provided by the user.
        favorite_authors: A list of the user's preferred authors for
            personalization.
        favorite_genres: A list of the user's preferred literary genres.
        reading_list: A list of book titles or IDs the user intended to read.
        books: A list of dictionaries containing metadata for specific book
            entities (e.g., title, author, availability).
    """

    message: Annotated[list[Any], operator.add]
    pending_tool_calls: list[dict]
    awaiting_approval: bool
    approval_granted: bool
    iteration_count: int
    should_exit: bool
    last_user_input: str
    favorite_authors: list[str]
    favorite_genres: list[str]
    reading_list: list[str]
    books: list[dict[str, Any]]
