AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Multi-tenant RAG with FastAPI
Globals:
  Function:
    Timeout: 30
    MemorySize: 512

# Inputs from samconfig.py
Parameters:
  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API key
    Default: ""

Resources:
  OpenAISecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: openai-api-key
      Description: OpenAI API key
      SecretString: !Sub |
        {
          "api_key": "${OpenAIApiKey}"
        }

  # AWS Lambda function definition
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/api/main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64

      Environment:
        Variables:
          OPENAI_SECRET_ARN: !Ref OpenAISecret

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref OpenAISecret

      Events:
        TestRoute:
          Type: Api # <- this creates API Gateway implicitly inside AWS
          Properties:
            Path: /
            Method: get
        AIQueryRoute:
          Type: Api
          Properties:
            Path: /ai/query
            Method: post
        AIChatRoute:
          Type: Api
          Properties:
            Path: /chat
            Method: post
        PdfUploadRoute:
          Type: Api
          Properties:
            Path: /data/upload_pdf
            Method: post
        WebContentUploadRoute:
          Type: Api
          Properties:
            Path: /data/upload_web_content
            Method: post
        UserLoginRoute:
          Type: Api
          Properties:
            Path: /user/login
            Method: post
        UserRegisterRoute:
          Type: Api
          Properties:
            Path: /user/register
            Method: post

Outputs:
  APIGatewayHost:
    Description: "API Gateway endpoint HOST for Prod stage for Item function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ItemFunction:
    Description: "Item Lambda Function ARN"
    Value: !GetAtt MainFunction.Arn
