AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A simple greeting application

Resources:
  GreetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambda_handler
      Runtime: python3.12
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          PYTHONUNBUFFERED: "1"
