"""add category description

Revision ID: ddc9889195d9
Revises: 38e6f1c50ad3
Create Date: 2025-12-03 13:38:19.128752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc9889195d9'
down_revision: Union[str, Sequence[str], None] = '38e6f1c50ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_category', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_category', 'description')
    # ### end Alembic commands ###
