"""add user_llm_cache table

Revision ID: 8de352645356
Revises: e179b863934f
Create Date: 2025-12-26 15:21:52.844551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de352645356'
down_revision: Union[str, Sequence[str], None] = 'e179b863934f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_llm_cache',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('llm', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('idx', 'user_id', 'llm', 'prompt')
    )
    op.create_index('idx_user_prompt', 'user_llm_cache', ['user_id', 'prompt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_prompt', table_name='user_llm_cache')
    op.drop_table('user_llm_cache')
    # ### end Alembic commands ###
