"""removed 3 cols from product, add product_category and linked it to product

Revision ID: 38e6f1c50ad3
Revises: 64efd624210d
Create Date: 2025-12-03 12:01:41.785914

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38e6f1c50ad3"
down_revision: Union[str, Sequence[str], None] = "64efd624210d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f("ix_product_id"), table_name="product")
    # op.drop_table('product')
    # op.drop_table('product_category')
    # op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=150), autoincrement=False, nullable=False),
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("user_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("user_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "product_category",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('product_category_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=25), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="product_category_pkey"),
        sa.UniqueConstraint(
            "name",
            name="product_category_name_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "product",
        sa.Column("id", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_category.id"],
            name=op.f("product_category_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("product_pkey")),
    )
    op.create_index(op.f("ix_product_id"), "product", ["id"], unique=True)
    # ### end Alembic commands ###
