"""add on delete cascade in products table

Revision ID: 6b0a3c79cfec
Revises: ac3227307319
Create Date: 2025-12-03 15:53:21.417208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0a3c79cfec'
down_revision: Union[str, Sequence[str], None] = 'ac3227307319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_category_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'product_category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_category_id_fkey'), 'product', 'product_category', ['category_id'], ['id'])
    # ### end Alembic commands ###
