"""add price_type column to product table

Revision ID: f031f9d2868e
Revises: 1cb154ef11a4
Create Date: 2025-12-04 17:44:11.799686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f031f9d2868e'
down_revision: Union[str, Sequence[str], None] = '1cb154ef11a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price_type', sa.String(length=50), server_default='regular', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price_type')
    # ### end Alembic commands ###
