"""update user_id as FK from user table

Revision ID: d39367971af1
Revises: 8de352645356
Create Date: 2025-12-26 15:27:17.082998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39367971af1'
down_revision: Union[str, Sequence[str], None] = '8de352645356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_llm_cache', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_llm_cache', type_='foreignkey')
    # ### end Alembic commands ###
